[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "lumenpay-bot"
version = "0.1.0"
description = "LumenPay Bot – платформа для управления платными подписками в Telegram."

